version: '3.8'

services:
  database:
    image: postgres:15
    container_name: event_platform_db
    environment:
      POSTGRES_DB: event_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event_platform_backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:password@database:5432/event_platform
      JWT_SECRET: your-secret-key-change-in-production
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event_platform_frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:4000/graphql
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
